# Driver Class Data -- Create
sam = Driver.create(name: "Samidh", car_model: "Lexus")
tom = Driver.create(name: "Tom", car_model: "Toyota")
lucas = Driver.create(name: "Lucas", car_model: "Honda")
tim = Driver.create(name: "Tim", car_model: "Tesla")
harry = Driver.create(name: "Harry", car_model: "Chrysler")
craig = Driver.create(name: "Craig", car_model: "Nissan")
jim = Driver.create(name: "Jim", car_model: "Cadillac")
ryan = Driver.create(name: "Ryan", car_model: "Lamborghini")
chris = Driver.create(name: "Chris", car_model: "Ferrari")
kevin = Driver.create(name: "Kevin", car_model: "McLaren")

# Passenger Class Data -- Create
jimmy = Passenger.create(name: "Jimmy")
timmy = Passenger.create(name: "Timmy")
drake = Passenger.create(name: "Drake")
mario = Passenger.create(name: "Mario")
arthur = Passenger.create(name: "Arthur")
daniel = Passenger.create(name: "Daniel")
brian = Passenger.create(name: "Brian")
thomas = Passenger.create(name: "Thomas")
chrissy = Passenger.create(name: "Chrissy")
nick = Passenger.create(name: "Nick")

# Review Class Data --  Create
Review.create(driver_id: sam.id, passenger_id: jimmy.id, reviews: "He is one of the best drivers in the world! Give him a raise!")
Review.create(driver_id: tom.id, passenger_id: timmy.id, reviews: "Wow, absolutely amazing!")
Review.create(driver_id: lucas.id, passenger_id: drake.id, reviews: "He was very welcoming. We talked through the whole ride!")
Review.create(driver_id: tim.id, passenger_id: mario.id, reviews: "He's very cautious, but still drives under the speed limit!")
Review.create(driver_id: harry.id, passenger_id: arthur.id, reviews: "He's british, and sort of a wizard. Did he just make the car dissapear?!")
Review.create(driver_id: craig.id, passenger_id: daniel.id, reviews: "This guy is so bad, I got out, when I had the chance!")
Review.create(driver_id: jim.id, passenger_id: brian.id, reviews: "Jim knows how to pull the best pranks ever!")
Review.create(driver_id: ryan.id, passenger_id: thomas.id, reviews: "This guy was very patient, but his car is off the chain!")
Review.create(driver_id: chris.id, passenger_id: chrissy.id, reviews: "He can dance and rap, but his Lambo stole the show!")
Review.create(driver_id: kevin.id, passenger_id: nick.id, reviews: "Kevin dropped the chili again! Atleast the car was fast")
